### ISSUE TITLE
Prototype HTML parser based importing

### ISSUE THREAD

**Issue by jtiala** [jtiala/lunchwatch-api#22]
Current importers are relying for the restaurant to provide some kind of json api. Having configurable HTML parsing would allow us to import other menus too.

**Comment by alberto-f** [comment]
Probably we need two strategies: server-side rendered page and client-side rendered page. Interesting functy that I actually need for another pet project. I will try to provide something in here at some point.

**Comment by alberto-f** [comment]
Hey, I have done some prototyping using **selenium** (for client-side rendering pages) or **request** (for server side rendering pages) and **cheerio** for scrapping the content downloaded in prev. step.

Prototyping went well. It seems to work but I have not integrated yet into this project.

Now, there are some issues I would like to discuss:

**Client-side rendering websites:**
Im using selenium to download website pages that are client-side rendered.

Some websites might have a direct URL to see the menu; others might required some *"click in this button to display menu"*. With Selenium we can interact with any website but it requires invoke "commands". This commands obviously are different for each website. I do not see how this commands can be saved in a database. This means that for every page for which we use selenium, we would need an **InteractiveRunner** that knows how to interact with the website to open the menu. Is that a problem?

**Server-side rendering websites:**
When we do a *HTTP GET* request to download page content, do we want to keep this file in a temporary directory? Keeping the HTML file in a temporary file would allow to compare file fingerprints, detecting if menu has been changed and need to be processed further or not.

**Comment by jtiala** [comment]
Hey, thanks for your prototyping and sorry for not getting back to you earlier. I've been super busy lately and kinda forgot about this.

Having separate runner for each client-side rendered website is not a problem. Universal importer for every client-rendered site would be cool, but saving the commands in database is probably way too complicated for this app, if its even possible.

As for server-side rendered websites, keeping file in temp directory is a good idea.

**Comment by thibaudcolas** [comment]
Target menus to try out / add:

- https://rooster.fi/lounas/
- https://oulunupseerikerho.fi/ravintola/lounas/

As far as I can tell both of those are server-rendered.

**Comment by alberto-f** [comment]
In two weeks I'm back to work. I can push the prototype to some branch then. I'm on paternity leave now 😁

**Comment by jtiala** [comment]
Added puppeteer-based html scraping in #31
